var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,g={next:function(){if(d<a.length){var l=d++;return{value:c(l,a[l]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(a,c,d,g){if(c){d=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var l=a[g];l in d||(d[l]={});d=d[l]}a=a[a.length-1];g=d[a];c=c(g);c!=g&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
var plgGdprAllCookiesDisabledByScript=!1,plgGdprObserverMutationTags=null,plgGdprCustomScriptExecutionGeneric=!1,detectedOldIPhone=!1;if(null!==navigator.userAgent.match(/iPhone/i)){var iphone4=480==window.screen.height,iphone5=568==window.screen.height;if(iphone4||iphone5)detectedOldIPhone=!0}
var plgGdprDisableAllCookies=function(a){var c=document.cookie.split("; "),d=["cookieconsent_status"];"undefined"!==typeof gdprJSessCook&&d.push(gdprJSessCook);"undefined"!==typeof gdprJAdminSessCook&&d.push(gdprJAdminSessCook);if(gdprConfigurationOptions.allowedCookies){var g=gdprConfigurationOptions.allowedCookies.split(",");d=d.concat(g)}g=function(a){for(var b=window.location.hostname.split(".");1<b.length;){var h=encodeURIComponent(a.split(";")[0].split("=")[0])+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain="+
b.join(".")+" ;path=",e=location.pathname.split("/");for(document.cookie=h+"/";0<e.length;){var f=e.join("/");f||(f="/");document.cookie=h+f;e.pop()}b.shift()}};for(var l=0;l<c.length;l++){for(var b=!0,f=0;f<d.length;f++)-1!=c[l].indexOf(d[f])&&(b=!1);b&&g(c[l])}if(!a&&gdprConfigurationOptions.blockCookieDefine&&!detectedOldIPhone){var e="undefined"!==typeof Document&&Document.prototype&&Object.getOwnPropertyDescriptor(Document.prototype,"cookie")||"undefined"!==typeof HTMLDocument&&HTMLDocument.prototype&&
Object.getOwnPropertyDescriptor(HTMLDocument.prototype,"cookie");e&&"function"===typeof e.get&&"function"===typeof e.set&&Object.defineProperty(document,"cookie",{configurable:!0,enumerable:!0,get:function(){return(e.get.call(document)||"").split("; ").filter(function(a){return 0===a.indexOf("cookieconsent_status=")}).join("; ")},set:function(a){"cookieconsent_status"===String(a).split("=")[0].trim()&&e.set.call(document,a);return!0}})}a=gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute?
",["+gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute+"*=gdprlock]":"";gdprConfigurationOptions.placeholderBlockedResources?jQuery("*[src*=gdprlock],*[data-source=gdprlock]"+a).filter(function(a,b){return"script"==b.nodeName.toLowerCase()||"link"==b.nodeName.toLowerCase()?!1:!0}).replaceWith(function(a){var b="";gdprConfigurationOptions.placeholderOnpageUnlock&&(a=this.attributes,"undefined"!==typeof a["data-original-src"]&&jQuery.each(a,function(a,e){"data-original-src"==e.name&&
(b+=" "+e.name+'="'+e.value+'"');-1==e.name.indexOf("data")&&(b+=" data-original-"+e.name+'="'+e.value+'"')}));return'<div class="gdprlock-placeholder"'+b+'><div class="gdprlock-placeholder-text">'+gdprConfigurationOptions.placeholderBlockedResourcesText+"</div></div>"}):jQuery("*[src*=gdprlock],*[data-source=gdprlock]"+a).remove();plgGdprAllCookiesDisabledByScript=!0},plgGdprShowReloadWindow=function(){gdprConfigurationOptions.showReloadMsg&&(jQuery("#gdpr_reload_msg").remove(),jQuery("<div/>").attr("id",
"gdpr_reload_msg").prependTo("body").append('<div id="gdpr_reload_msgtext"><span id="gdpr_reload_info_icon">&#x24D8;</span>'+gdprConfigurationOptions.showReloadMsgText+"</div>").css("margin-top",0).hide().fadeIn(500).delay(2500).fadeOut(500,function(){jQuery(this).remove()}));window.location.reload()};
if(gdprConfigurationOptions.autoDetectYoutubePoster){var getYouTubePoster=function(a,c){(c=function(a){return(a=a.match(/(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/))?a[1]:null}(c))&&fetch("https://www.googleapis.com/youtube/v3/videos?id="+c+"&key="+gdprConfigurationOptions.autoDetectYoutubePosterApikey+"&part=snippet").then(function(a){return a.json()}).then(function(c){c=c.items[0].snippet.thumbnails.maxres.url;
jQuery(a).css({background:"url("+c+") no-repeat","background-size":"contain"})}).catch(function(a){})};setTimeout(function(){jQuery('div.gdprlock-placeholder[data-original-src*="youtube"],div.gdprcookielock-placeholder[data-original-src*="youtube"]').each(function(a,c){a=jQuery(c).data("original-src");getYouTubePoster(c,a)})},1)}
var plgGdprCssEscape=function(a){var c=String(a),d=c.length,g=-1,l="",b=c.charCodeAt(0);if(48<=b&&57>=b)return a;for(;++g<d;)a=c.charCodeAt(g),l=0==a?l+"\ufffd":1<=a&&31>=a||127==a||0==g&&48<=a&&57>=a||1==g&&48<=a&&57>=a&&45==b?l+("\\"+a.toString(16)+" "):0==g&&1==d&&45==a?l+("\\"+c.charAt(g)):128<=a||45==a||95==a||48<=a&&57>=a||65<=a&&90>=a||97<=a&&122>=a?l+c.charAt(g):l+("\\"+c.charAt(g));return l};
(function(){if("undefined"!==typeof gdpr_unset_categories_cookies)for(var a=0;a<gdpr_unset_categories_cookies.length;a++)for(var c=gdpr_unset_categories_cookies[a],d=window.location.hostname.split(".");1<d.length;){var g=encodeURIComponent(c.split(";")[0].split("=")[0])+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain="+d.join(".")+" ;path=",l=location.pathname.split("/");for(document.cookie=g+"/";0<l.length;){var b=l.join("/");b||(b="/");document.cookie=g+b;l.pop()}d.shift();gdprConfigurationOptions.blockLocalStorage&&
localStorage.removeItem(c);gdprConfigurationOptions.blockSessionStorage&&sessionStorage.removeItem(c)}})();gdprConfigurationOptions.lawByCountry||("opt-in"!=gdprConfigurationOptions.complianceType||localStorage.getItem("hasConsented")||localStorage.getItem("setConsentedCookie")||plgGdprDisableAllCookies(),"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("hasDeclined")&&plgGdprDisableAllCookies());
gdprConfigurationOptions.optoutIndividualResources&&function(){var a=localStorage.getItem("gdprCookiesChoices");a&&(a=JSON.parse(a));a&&function(){for(var c=document.cookie.split("; "),b=0;b<c.length;b++){var f=!1,e=encodeURIComponent(c[b].split(";")[0].split("=")[0]);e in a&&(f=!0);if(f){f=c[b];for(var h=window.location.hostname.split(".");1<h.length;){var k=encodeURIComponent(f.split(";")[0].split("=")[0])+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain="+h.join(".")+" ;path=",p=location.pathname.split("/");
for(document.cookie=k+"/";0<p.length;){var d=p.join("/");d||(d="/");document.cookie=k+d;p.pop()}h.shift()}gdprConfigurationOptions.blockLocalStorage&&localStorage.removeItem(e);gdprConfigurationOptions.blockSessionStorage&&sessionStorage.removeItem(e)}}}();if(a){var c=[],d=gdprConfigurationOptions.externalAdvancedBlockingModeTags.toLowerCase().split(","),g=function(c){var b=!1,f=c.nodeName.toLowerCase();if(-1==jQuery.inArray(f,d))return b;jQuery.each(a,function(e){if(!a[e]&&-1<c.outerHTML.indexOf(e)&&
-1==c.outerHTML.indexOf("gdpr"))return b=e,!0});return b};plgGdprObserverMutationTags=new MutationObserver(function(a){for(var b=0;b<a.length;b++)for(var f=a[b].addedNodes,e=0;e<f.length;e++){var h=f[e],k=h.nodeName.toLowerCase();-1==jQuery.inArray(k,c)&&c.push(k);if(1===h.nodeType&&(k=g(h))){var d=function(a){"script"===h.nodeName&&a.preventDefault();h.removeEventListener("beforescriptexecute",d)};h.addEventListener("beforescriptexecute",d);if(gdprConfigurationOptions.placeholderBlockedResources&&
"script"!=h.nodeName.toLowerCase()&&"link"!=h.nodeName.toLowerCase()){var l=gdprConfigurationOptions.placeholderIndividualBlockedResourcesAction?"gdprlock-placeholder ":"",n="";gdprConfigurationOptions.placeholderOnpageUnlock&&"iframe"==h.nodeName.toLowerCase()&&jQuery.each(h.attributes,function(a,b){n+=" data-original-"+b.name+'="'+b.value+'"'});jQuery(h).replaceWith('<div class="'+l+'gdprcookielock-placeholder"'+n+'><div class="gdprcookielock-placeholder-text">'+gdprConfigurationOptions.placeholderIndividualBlockedResourcesText.replace("{domain}",
k)+"</div></div>")}else jQuery(h).remove()}}});plgGdprObserverMutationTags.observe(document.documentElement,{childList:!0,subtree:!0});setTimeout(function(){jQuery.each(d,function(d,b){-1==jQuery.inArray(b,c)&&jQuery.each(a,function(f){if(!a[f]){var e=jQuery(b+'[src*="'+f+'"], '+b+'[href*="'+f+'"], '+b+'[poster*="'+f+'"]');if(gdprConfigurationOptions.placeholderBlockedResources&&"script"!=b&&"link"!=b){var h=gdprConfigurationOptions.placeholderIndividualBlockedResourcesAction?"gdprlock-placeholder ":
"";e.replaceWith(function(a){var e="";gdprConfigurationOptions.placeholderOnpageUnlock&&"iframe"==b&&jQuery.each(this.attributes,function(a,b){e+=" data-original-"+b.name+'="'+b.value+'"'});return'<div class="'+h+'gdprcookielock-placeholder"'+e+'><div class="gdprcookielock-placeholder-text">'+gdprConfigurationOptions.placeholderIndividualBlockedResourcesText.replace("{domain}",f)+"</div></div>"})}else e.remove()}})})},500)}a&&(d=gdprConfigurationOptions.externalAdvancedBlockingModeTags.toLowerCase().split(","),
jQuery.each(a,function(c){if(!a[c]){var b=plgGdprCssEscape(c),f=gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute?",["+gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute+"*="+b+"]":"";jQuery.each(d,function(a,h){jQuery(h+"[src*="+b+"],"+h+"[href*="+b+"]"+f).each(function(a,b){if(gdprConfigurationOptions.placeholderBlockedResources&&"script"!=b.nodeName.toLowerCase()&&"link"!=b.nodeName.toLowerCase()){a=gdprConfigurationOptions.placeholderIndividualBlockedResourcesAction?
"gdprlock-placeholder ":"";var e="";gdprConfigurationOptions.placeholderOnpageUnlock&&"iframe"==b.nodeName.toLowerCase()&&jQuery.each(this.attributes,function(a,b){e+=" data-original-"+b.name+'="'+b.value+'"'});jQuery(b).replaceWith('<div class="'+a+'gdprcookielock-placeholder"'+e+'><div class="gdprcookielock-placeholder-text">'+gdprConfigurationOptions.placeholderIndividualBlockedResourcesText.replace("{domain}",c)+"</div></div>")}else jQuery(b).remove()})})}}))}();
jQuery(function(a){if(!plgGdprAllCookiesDisabledByScript){var c=gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute?",["+gdprConfigurationOptions.externalAdvancedBlockingModeCustomAttribute+"*=gdprlock]":"";gdprConfigurationOptions.placeholderBlockedResources?a("*[src*=gdprlock],*[data-source=gdprlock]"+c).filter(function(a,c){return"script"==c.nodeName.toLowerCase()||"link"==c.nodeName.toLowerCase()?!1:!0}).replaceWith(function(b){var c="";gdprConfigurationOptions.placeholderOnpageUnlock&&
(b=this.attributes,"undefined"!==typeof b["data-original-src"]&&a.each(b,function(a,b){"data-original-src"==b.name&&(c+=" "+b.name+'="'+b.value+'"');-1==b.name.indexOf("data")&&(c+=" data-original-"+b.name+'="'+b.value+'"')}));return"undefined"===typeof this.dataset.gdprDomain?'<div class="gdprlock-placeholder"'+c+'><div class="gdprlock-placeholder-text">'+gdprConfigurationOptions.placeholderBlockedResourcesText+"</div></div>":'<div class="'+(gdprConfigurationOptions.placeholderIndividualBlockedResourcesAction?
"gdprlock-placeholder ":"")+'gdprcookielock-placeholder"'+c+'><div class="gdprcookielock-placeholder-text">'+gdprConfigurationOptions.placeholderIndividualBlockedResourcesText.replace("{domain}",this.dataset.gdprDomain)+"</div></div>"}):jQuery("*[src*=gdprlock],*[data-source=gdprlock]"+c).remove()}window.gdprIsCookieConsentPresent=function(a){a=("; "+document.cookie).split("; "+a+"=");return 2!=a.length?void 0:a.pop().split(";").shift()}("cookieconsent_status");var d=function(){var b=a("iframe").length,
c=!!navigator.mozGetUserMedia;gdprConfigurationOptions.blockExternalCookiesDomains&&b&&c&&localStorage.setItem("refreshIframeCache",!0);if(gdpr_enable_log_cookie_consent){if("opt-in"==gdprConfigurationOptions.complianceType)var e=localStorage.getItem("hasConsented");else"opt-out"==gdprConfigurationOptions.complianceType&&(e=!localStorage.getItem("hasDeclined"));a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:e?
1:0}}).then(function(){plgGdprShowReloadWindow()})}else setTimeout(function(){plgGdprShowReloadWindow()},0)},g=function(){plgGdprObserverMutationTags&&plgGdprObserverMutationTags.disconnect();a.ajax({type:"POST",dataType:"json",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.getDomainsSum",data:{noredirect:1}}).then(function(b){b=Object.keys(b).map(function(a){return b[a]});var c=localStorage.getItem("gdprCookiesChoices");c&&(c=JSON.parse(c),a.each(c,function(a){c[a]||b.push(a)}));a("div.gdprlock-placeholder[data-original-src],div.gdprcookielock-placeholder[data-original-src]").replaceWith(function(c){var e=
"";c=this.attributes;if("undefined"!==typeof c["data-original-src"]){for(var d in b)if(-1<c["data-original-src"].value.indexOf(b[d]))return this;a.each(c,function(a,b){0==b.name.indexOf("data-original-")&&(e+=b.name.replace("data-original-","")+'="'+b.value+'" ')});return"<iframe "+e+"></iframe>"}});a.each(b,function(b,c){b=plgGdprCssEscape(c);a("iframe[src*="+b+"]").each(function(b,e){b=gdprConfigurationOptions.placeholderIndividualBlockedResourcesAction?"gdprlock-placeholder ":"";var d="";a.each(this.attributes,
function(a,b){d+=" data-original-"+b.name+'="'+b.value+'"'});a(e).replaceWith('<div class="'+b+'gdprcookielock-placeholder"'+d+'><div class="gdprcookielock-placeholder-text">'+gdprConfigurationOptions.placeholderIndividualBlockedResourcesText.replace("{domain}",c)+"</div></div>")})});gdprConfigurationOptions.autoDetectYoutubePoster&&a('div.gdprlock-placeholder[data-original-src*="youtube"],div.gdprcookielock-placeholder[data-original-src*="youtube"]').each(function(b,c){b=a(c).data("original-src");
getYouTubePoster(c,b)})})},l=function(){plgGdprObserverMutationTags&&plgGdprObserverMutationTags.disconnect();a.ajax({type:"POST",dataType:"json",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.getDomainsSum",data:{noredirect:1}}).then(function(b){b=Object.keys(b).map(function(a){return b[a]});var c=localStorage.getItem("gdprCookiesChoices");c&&(c=JSON.parse(c),a.each(c,function(a){c[a]||b.push(a)}));a("script[data-gdprlock-original-script-src]").replaceWith(function(c){c=this.attributes;
if("undefined"!==typeof c["data-gdprlock-original-script-src"]){for(var e in b)if(-1<c["data-gdprlock-original-script-src"].value.indexOf(b[e]))return this;a.getScript(c["data-gdprlock-original-script-src"].value);a(this).attr("src",c["data-gdprlock-original-script-src"].value).removeAttr("data-gdprlock-original-script-src").removeAttr("data-source");return this}});a.each(b,function(b,c){b=plgGdprCssEscape(c);a("script[src*="+b+"]").each(function(b,c){b=a(c).attr("src");a(c).attr("data-gdprlock-original-script-src",
b).attr("data-source","gdprlock");a(c).removeAttr("src")})})})};a(document).on("click","a.cc-allow",function(b){"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("hasDeclined")&&(localStorage.removeItem("hasDeclined"),localStorage.removeItem("hasDenyMessage"),localStorage.removeItem("hasExplititDeclinedAll"),localStorage.setItem("setAllowRevokedCookie",!0),d());gdpr_enable_log_cookie_consent&&"opt-out"==gdprConfigurationOptions.complianceType&&!localStorage.getItem("hasFirstDeclined")&&
a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:1}})});localStorage.getItem("refreshIframeCache")&&(a("iframe").each(function(b,c){b=a(c).clone();a(c).after(b).remove()}),localStorage.getItem("setConsentedCookie")||localStorage.removeItem("refreshIframeCache"));window.cookieconsent.initialise({type:gdprConfigurationOptions.complianceType,layout:gdprConfigurationOptions.toolbarLayout,theme:gdprConfigurationOptions.toolbarTheme,
centertheme:gdprConfigurationOptions.toolbarCenterTheme,position:gdprConfigurationOptions.toolbarPosition,revokeposition:gdprConfigurationOptions.revokePosition,container:document.querySelector(gdprConfigurationOptions.containerSelector),palette:{popup:{background:gdprConfigurationOptions.popupBackground,text:gdprConfigurationOptions.popupText,link:gdprConfigurationOptions.popupLink,effect:gdprConfigurationOptions.popupEffect},button:{background:gdprConfigurationOptions.buttonBackground,border:gdprConfigurationOptions.buttonBorder,
text:gdprConfigurationOptions.buttonText},highlight:{background:gdprConfigurationOptions.highlightBackground,border:gdprConfigurationOptions.highlightBorder,text:gdprConfigurationOptions.highlightText},highlightDismiss:{background:gdprConfigurationOptions.highlightDismissBackground,border:gdprConfigurationOptions.highlightDismissBorder,text:gdprConfigurationOptions.highlightDismissText},highlightOpacity:{opacity:gdprConfigurationOptions.highlightOpacity},buttonall:{background:gdprConfigurationOptions.allowallButtonBackground,
border:gdprConfigurationOptions.allowallButtonBorder,text:gdprConfigurationOptions.allowallButtonText},buttonSettings:{background:gdprConfigurationOptions.toggleCookieSettingsButtonBackground,border:gdprConfigurationOptions.toggleCookieSettingsButtonBorder,text:gdprConfigurationOptions.toggleCookieSettingsButtonText}},revokable:!!gdprConfigurationOptions.revokable,location:!!gdprConfigurationOptions.lawByCountry,law:{regionalLaw:!gdprConfigurationOptions.lawByCountry},showLink:!!gdprConfigurationOptions.showLinks,
static:!gdprConfigurationOptions.toolbarPositionmentType,dismissOnScroll:gdprConfigurationOptions.dismissOnScroll,dismissOnTimeout:gdprConfigurationOptions.dismissOnTimeout,animateRevokable:!!gdprConfigurationOptions.hideRevokableButton,onInitialise:function(a){"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("setAllowRevokedCookie")&&(this.setStatus("allow",!0),localStorage.removeItem("setAllowRevokedCookie"),d())},content:{header:gdprConfigurationOptions.headerText,message:gdprConfigurationOptions.messageText,
dismiss:gdprConfigurationOptions.dismissText,allow:gdprConfigurationOptions.allowText,deny:gdprConfigurationOptions.denyText,allowall:gdprConfigurationOptions.allowallText,link:gdprConfigurationOptions.cookiePolicyLinkText,href:gdprConfigurationOptions.cookiePolicyLink,privacylink:gdprConfigurationOptions.privacyPolicyLinkText,privacyhref:gdprConfigurationOptions.privacyPolicyLink},onStatusChange:function(b,c){c=this.options.type;var e=this.hasConsented();if("opt-in"==c&&(e||a("a.cc-btn",this.element).hasClass("cc-allow"))&&
"allow"==b){var h=localStorage.getItem("hasConsented"),k=localStorage.getItem("hasExplititDeclinedAll"),f={hasConsented:!0,timestamp:(new Date).getTime()};localStorage.setItem("hasConsented",JSON.stringify(f));plgGdprAllCookiesDisabledByScript&&("hard"==gdprConfigurationOptions.declineButtonBehavior||gdprConfigurationOptions.blockCookieDefine&&"soft"==gdprConfigurationOptions.declineButtonBehavior)&&localStorage.setItem("setConsentedCookie",!0);localStorage.removeItem("hasExplititDeclinedAll");gdprConfigurationOptions.preserveLockedCategories?
a("input.cc-cookie-checkbox:not([readonly])").attr("disabled",!1):a("input.cc-cookie-checkbox").attr("disabled",!1);if(gdprConfigurationOptions.disableFirstReload){f=!1;var r=parseInt(localStorage.getItem("autoActivateOnNextPage")),n=!localStorage.getItem("hasFirstAccepted");if(!n||1==r||k)h&&gdprIsCookieConsentPresent||(f=!0,d());gdpr_enable_log_cookie_consent&&n&&!f&&a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:1}});
n&&(f={hasFirstAccepted:!0,timestamp:(new Date).getTime()},localStorage.setItem("hasFirstAccepted",JSON.stringify(f)));"center"==gdprConfigurationOptions.toolbarPosition&&gdprConfigurationOptions.positionCenterBlurEffect&&n&&a("body").css({filter:"none","pointer-events":"all"})}else h&&gdprIsCookieConsentPresent||d();if("soft"==gdprConfigurationOptions.declineButtonBehavior&&!gdprConfigurationOptions.preserveLockedCategories){var m=1;"slow"==gdprConfigurationOptions.allowallButtonTimingAjax&&(m=2);
"extrafast"==gdprConfigurationOptions.allowallButtonTimingAjax&&(m=.5);for(k=1;4>=k;k++)setTimeout(function(b){a("input[id=cookie_cat"+b+"][readonly]:not(:checked)").trigger("click").prop("checked",!0)},400*k*m,k)}gdprConfigurationOptions.placeholderOnpageUnlock&&setTimeout(function(){g()},250);gdprConfigurationOptions.scriptsOnpageUnlock&&setTimeout(function(){l()},500);gdprConfigurationOptions.enableCustomScriptExecGeneric&&!plgGdprCustomScriptExecutionGeneric&&(h=document.createElement("script"),
h.innerHTML=gdprConfigurationOptions.customScriptExecGeneric,document.head.appendChild(h),plgGdprCustomScriptExecutionGeneric=!0)}if("opt-in"==c&&(!e||a("a.cc-btn",this.element).hasClass("cc-deny"))&&"deny"==b){h=localStorage.getItem("hasConsented");localStorage.removeItem("hasConsented");localStorage.removeItem("setConsentedCookie");f={hasDeclined:!0,timestamp:(new Date).getTime()};localStorage.setItem("hasFirstDeclined",JSON.stringify(f));localStorage.setItem("hasExplititDeclinedAll",JSON.stringify(f));
if("hard"==gdprConfigurationOptions.declineButtonBehavior)if(this.setStatus("deny",!0),gdprConfigurationOptions.preserveLockedCategories){if(a("input.cc-cookie-checkbox:not([readonly])").attr("disabled",!0).prop("checked",!1),a("div.cc-checkboxes-container input.cc-cookie-checkbox:not([readonly]):checked + span").addClass("cc-checkbox-switcher-category-transitioning"),k=!!jQuery("div.gdpr-component-view").length||!1)k=a("input.cc-cookie-checkbox:not([readonly])").parents("div.gdpr-component-view"),
a("div.gdpr_cookie_switcher",k).addClass("inactive")}else a("input.cc-cookie-checkbox").attr("disabled",!0).prop("checked",!1),a("div.cc-checkboxes-container input.cc-cookie-checkbox:checked + span").addClass("cc-checkbox-switcher-category-transitioning"),(k=!!jQuery("div.gdpr-component-view").length||!1)&&a("div.gdpr_cookie_switcher").addClass("inactive");else if(this.setStatus("allow",!0),localStorage.removeItem("hasExplititDeclinedAll"),localStorage.removeItem("hasFirstAccepted"),m=1,"slow"==gdprConfigurationOptions.allowallButtonTimingAjax&&
(m=2),"extrafast"==gdprConfigurationOptions.allowallButtonTimingAjax&&(m=.5),gdprConfigurationOptions.preserveLockedCategories){for(k=1;4>=k;k++)setTimeout(function(b){a("input[id=cookie_cat"+b+"]:checked:not([readonly])").trigger("click").prop("checked",!1)},400*k*m,k);if(k=!!jQuery("div.gdpr-component-view").length||!1)k=a("input.cc-cookie-checkbox:not([readonly])").parents("div.gdpr-component-view"),a("div.gdpr_cookie_switcher",k).addClass("inactive")}else{for(k=1;4>=k;k++)setTimeout(function(b){a("input[id=cookie_cat"+
b+"]:checked").trigger("click").prop("checked",!1)},400*k*m,k);(k=!!jQuery("div.gdpr-component-view").length||!1)&&a("div.gdpr_cookie_switcher").addClass("inactive")}if(h)"hard"==gdprConfigurationOptions.declineButtonBehavior?d():setTimeout(function(){gdprConfigurationOptions.alwaysReloadAfterCategoriesChange&&window.cookieconsent.cookieCategoriesHasChanged?d():gdpr_enable_log_cookie_consent&&a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",
data:{gdpr_generic_cookie_consent:0}});gdprConfigurationOptions.placeholderOnpageUnlock&&setTimeout(function(){g()},250);gdprConfigurationOptions.scriptsOnpageUnlock&&setTimeout(function(){l()},500)},2E3*m);else{var q=function(){gdprConfigurationOptions.autoRedirectOnDecline&&gdprConfigurationOptions.autoRedirectOnDeclineLink?window.location.href=gdprConfigurationOptions.autoRedirectOnDeclineLink:(gdprConfigurationOptions.reloadOnfirstDeclineall&&"undefined"!==typeof gdprUseCookieCategories&&plgGdprShowReloadWindow(),
"center"==gdprConfigurationOptions.toolbarPosition&&gdprConfigurationOptions.positionCenterBlurEffect&&gdprConfigurationOptions.positionCenterBlurEffectAlwaysFirstVisit&&a("body").css({filter:"none","pointer-events":"all"}))};gdpr_enable_log_cookie_consent?"hard"==gdprConfigurationOptions.declineButtonBehavior?a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:0}}).then(function(){q()}):setTimeout(function(){a.ajax({type:"POST",
url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:0}}).then(function(){q()})},2E3*m):q()}}if("opt-out"==c&&!e&&!localStorage.getItem("hasDeclined")){plgGdprDisableAllCookies(!0);f={hasDeclined:!0,timestamp:(new Date).getTime()};if(gdprConfigurationOptions.autoRedirectOnDecline&&gdprConfigurationOptions.autoRedirectOnDeclineLink&&!localStorage.getItem("hasFirstDeclined")){window.location.href=gdprConfigurationOptions.autoRedirectOnDeclineLink;
return}localStorage.setItem("hasDeclined",JSON.stringify(f));localStorage.setItem("hasFirstDeclined",JSON.stringify(f));localStorage.setItem("hasExplititDeclinedAll",JSON.stringify(f));gdprConfigurationOptions.preserveLockedCategories?a("input.cc-cookie-checkbox:not([readonly])").attr("disabled",!0):a("input.cc-cookie-checkbox").attr("disabled",!0);d()}"opt-out"==c&&(e||a("a.cc-btn",this.element).hasClass("cc-allow"))&&"allow"==b&&(gdprConfigurationOptions.placeholderOnpageUnlock&&setTimeout(function(){g()},
250),gdprConfigurationOptions.scriptsOnpageUnlock&&setTimeout(function(){l()},500),gdprConfigurationOptions.enableCustomScriptExecGeneric&&!plgGdprCustomScriptExecutionGeneric&&(h=document.createElement("script"),h.innerHTML=gdprConfigurationOptions.customScriptExecGeneric,document.head.appendChild(h),plgGdprCustomScriptExecutionGeneric=!0));gdprConfigurationOptions.denyMessageEnabled&&"allow"==b&&localStorage.removeItem("hasDenyMessage")},onPopupOpen:function(b){"opt-in"!=gdprConfigurationOptions.complianceType&&
"opt-out"!=gdprConfigurationOptions.complianceType||!gdprConfigurationOptions.autoAcceptOnNextPage||b||localStorage.getItem("hasExplititDeclinedAll")||(b=localStorage.getItem("autoActivateOnNextPage"),2==parseInt(b)?(localStorage.setItem("autoActivateOnNextPage",1),"opt-in"==gdprConfigurationOptions.complianceType?(a("div.cc-window.cc-banner,div.cc-window.cc-floating").hide(),a("a.cc-btn.cc-allow").trigger("click")):"opt-out"==gdprConfigurationOptions.complianceType&&setTimeout(function(){a("a.cc-btn.cc-allow").trigger("click")},
100)):b||localStorage.setItem("autoActivateOnNextPage",2))}});if(gdprConfigurationOptions.trackExistingCheckboxSelectors)a(gdprConfigurationOptions.trackExistingCheckboxSelectors).on("change",function(b){parentForm=a(b.target).parents("form");(b=a(b.target).attr("id")||a(b.target).attr("name")||"")&&(b+=" / ");var c={url:a(location).attr("href"),formid:b+(parentForm.attr("id")||""),formname:parentForm.attr("name"),formfields:{}};b=a(this);var e=b.attr("type"),d=parseInt(b.val());"checkbox"==e&&0===
d&&b.val(1);a(this).is(":checked")&&0!=parseInt(a(this).val())?(b=gdprConfigurationOptions.trackExistingCheckboxConsentLogsFormfields.split(","),b=b.map(function(a,b){return a.trim()}),a.each(b,function(b,d){b=a("input[name*="+d+"]:not(:hidden), input[id*="+d+"]:not(:hidden), textarea[name*="+d+"], textarea[id*="+d+"]",parentForm);b.length&&a.each(b,function(b,d){(b=a(d).attr("id"))||(b=a(d).attr("name"));b=b.replace(/[-_]/gi," ");b=b.replace(/[\[\]]/gi,"");b=b.replace("jform","");b=b.trim();d=a(d).val();
c.formfields[b]=d})}),a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.storeConsent&format=raw",data:c})):a.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.deleteConsent&format=raw",data:c})})});
